export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';


export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const DELETE_DATA_FAILURE = 'DELETE_DATA_FAILURE';


export const POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS"

export const USER_REQ="USER_REQ"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_TOTAL_PAGE="GET_TOTAL_PAGE"


export const SINGLE_USER_REQ="SINGLE_USER_REQ"
export const SINGLE_USER_SUCCESS="SINGLE_USER_SUCCESS"

